vacations = ['scotland', 'ireland', 'greece', 'florence', 'russia']
print(vacations)
print(sorted(vacations))
print(vacations)
print(sorted(vacations, reverse=True))
print(vacations)
vacations.reverse()
print(vacations)
vacations.reverse()
print(vacations)
vacations.sort()
print(vacations)
vacations.sort(reverse=True)
print(vacations)
