cd desktop
cd CSCI1301
cd ClassifyMessage	
cd bin
echo smoke 40.499812 -105.012075 its raining ash| Java ClassifyMessage
echo offer 40.022 -105.226 free essential supplies 4 evacs pets, 2323 55th st, boulder| Java ClassifyMessage
echo structure 40.029854 -105.391055 damaged:  224 left fork road (shed) (house okay)| Java ClassifyMessage
echo wind 40.3523 -105.2045 just switched, and now the smoke is thick around our house| Java ClassifyMessage
echo fire 40.0515 -105.332 firefighter sees a glow: sw from west coach rd toward sunshine canyon| Java ClassifyMessage
echo structure 40.050904 -105.373941 damaged: unknown number, by 204 gold run road| Java ClassifyMessage
echo evac 40.383 -105.113  overflow shltr 4 evacuees at walt clark middle school, loveland| Java ClassifyMessage
echo nofire 40.367 -105.292 activity: west of the pinewood res dam| Java ClassifyMessage
echo photo 40.052304 -105.319374 local: wild horse| Java ClassifyMessage
echo info 40.499812 -105.012075 its raining ash: windsor, co| Java ClassifyMessage
echo need  40.011471 -105.28638 volunteers sun 8a-10p donation ctr 2 help w/donations for victims and firefighters: 3111 28th st| Java ClassifyMessage
echo need  40.031131 -105.259259 people to help sort donations  Sept 12 8am-9pm 3111 28th st| Java ClassifyMessage
echo open 40.072208 -105.354437 evacuees can return to homes: lee hill| Java ClassifyMessage
echo open 40.076431 -105.309757 lee hill dr.| Java ClassifyMessage
